name: Examen2

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests with Gradle
        run: ./gradlew test

      - name: Unit Test (Debug)
        run: ./gradlew testDebugUnitTest

      - name: Generate Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
